server:
  applicationConnectors:
    - type: http
      port: 8023
  adminConnectors:
    - type: http
      port: 8923

logging:
  level: INFO
  appenders:
    - type: console
      threshold: INFO
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout
    
jerseyClient:
  timeout: 10000ms
  connectionTimeout: 10000ms
  connectionRequestTimeout: 10000ms
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: false
  gzipEnabledForRequests: false
  chunkedEncodingEnabled: false

mongo:
    uri: mongodb://mongoserver:27017/?&w=majority&wtimeoutMS=5000
    database: lighttracker

sendalSoftwareService:
    scs3pssId: <your PSS ID>
    apiKey: <your API key>
    secretKey: <your API secret>
    scsUrl: https://s3psiapi.sendal.tech
